/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package earth.levi

import java.io.File
import kotlin.test.assertTrue
import kotlin.test.Test
import org.gradle.testkit.runner.GradleRunner
import org.junit.jupiter.api.io.TempDir

/**
 * A simple functional test for the 'earth.levi.greeting' plugin.
 */
class FilterPrereleasePluginFunctionalTest {

    @field:TempDir
    lateinit var projectDir: File

    private val buildFile by lazy { projectDir.resolve("app/build.gradle") }
    private val settingsFile by lazy { projectDir.resolve("settings.gradle") }

    @Test fun `can run task`() {
        projectDir.resolve("app").mkdir()

        // Set up the test build
        settingsFile.writeText("include(\"app\")")
        buildFile.writeText("""
            plugins {
                id('earth.levi.filter-prerelease')
                id('java')  
            }   
            
            filterPrerelease {
                allowReleaseCandidate = true
            }
            
            repositories {
                mavenCentral()
            }                    
            
            dependencies {
              implementation 'app.cash.sqldelight:sqlite-driver:2.0.0'
            }
        """.trimIndent())

        // Run the build
        val runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments(":app:dependencies")
        runner.withProjectDir(projectDir)
        val result = runner.build()

        // Verify the result
        assertTrue(result.output.contains("app.cash.sqldelight:sqlite-driver:2.0.0"))
    }
}
