/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    application
    id("maven-publish")
}

repositories {
    mavenCentral()
}

dependencies {}

publishing {
    publications {
        register<MavenPublication>("plugin") {
            from(components["java"])
            groupId = "earth.levi"
            artifactId = "gradle-filter-prerelease-test-artifact"
            version = System.getenv("VERSION")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
//java {
//    toolchain {
        //languageVersion.set(JavaLanguageVersion.of(17))
    //}
//}

application {
    // Define the main class for the application.
    mainClass.set("earth.levi.App")
}
