name: Deploy plugin 

on: 
  push:    
    branches: ['main', 'beta', 'alpha']

jobs:
  deploy:
    name: Create tag, deploy binaries
    permissions:
      contents: write # to push git tags and github releases       
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup

      - name: Deploy git tag and Gradle plugin release via Semantic Release 
        uses: cycjimmy/semantic-release-action@v3
        with: 
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}